// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const browser: typeof import('wxt/browser')['browser']
  const clearConnectionError: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['clearConnectionError']
  const clearStoredData: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['clearStoredData']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createJobPage: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/notion')['createJobPage']
  const createNotionDatabase: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/notion')['createNotionDatabase']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getConnectionError: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['getConnectionError']
  const getStoredData: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['getStoredData']
  const injectScript: typeof import('wxt/client')['injectScript']
  const parseDeadline: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/sanitize')['parseDeadline']
  const parseNotionId: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/notion')['parseNotionId']
  const sanitizeText: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/sanitize')['sanitizeText']
  const setConnectionError: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['setConnectionError']
  const setStoredData: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['setStoredData']
  const storage: typeof import('wxt/storage')['storage']
  const updateDatabaseId: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/storage')['updateDatabaseId']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const validateDatabase: typeof import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/notion')['validateDatabase']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { SiteKey, JobData, StorageData, ConnectionError, AuthStatus, BackgroundMessage, ScrapeMessage, BackgroundResponse, ScrapeResponse, NotionTokenResponse } from 'C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/types'
  import('C:/Users/이인준/.gemini/antigravity/scratch/notion-job-scraper/extension/utils/types')
}
